file_input = input("Enter file to be read: ")
file = open(file_input, 'r')
line1 = file.readline()
line1 = line1.rstrip()
prevx, prevy = line1.split(' ')
prevx = int(prevx)
prevy = int(prevy)
print(prevx)
print(prevy)
